[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@layerzerolabs/onft-evm/=lib/devtools/packages/onft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

[rpc_endpoints]
base = "${BASE_SEPOLIA_RPC}"
optimism = "${OPTIMISM_SEPOLIA_RPC}"
arbitrum = "${ARBITRUM_SEPOLIA_RPC}"